# Android Gradle Plugin version
androidGradlePlugin = "8.4.0"
kotlin = "1.9.22"
composeCompiler = "1.5.12"
composeBom = "2024.02.00"
coreKtx = "1.13.1"
lifecycle = "2.7.0"
room = "2.6.1"
ktor = "2.3.9"
coil = "2.5.0"
accompanist = "0.32.0"
material3 = "1.2.1"
activity = "1.8.2"
navigation = "2.7.6"
hilt = "2.48"
workManager = "2.9.0"